# 02 – Python- und NumPy-Basics

## Lernziele

Du lernst wichtige Python-Datentypen, Kontrollstrukturen, Funktionen und den Umgang mit NumPy-Arrays. Diese Grundlagen begegnen uns später in jedem ML-Projekt.

## 1. Variablen und grundlegende Datentypen

In [1]:
kurs = "Machine Learning"   # str
anzahl_teilnehmende = 18       # int
lernrate = 0.01                # float
ist_aktiv = True               # bool

print(kurs, anzahl_teilnehmende, lernrate, ist_aktiv)
print(type(lernrate))

Machine Learning 18 0.01 True
<class 'float'>


Python ist dynamisch typisiert: Der Typ gehört zum Wert und muss nicht vorab deklariert werden. Sinnvolle Variablennamen sind wichtiger als kurze Namen. Kommentare erklären das **Warum**, nicht jede offensichtliche Zeile.

## 2. Listen, Tupel, Dictionaries und Sets

In [2]:
messwerte = [12.1, 11.8, 12.5, 13.0]      # geordnet, veränderbar
form = (28, 28)                            # geordnet, unveränderbar
person = {"name": "Ada", "alter": 36}  # Schlüssel -> Wert
klassen = {"Katze", "Hund", "Katze"}    # eindeutige Werte

messwerte.append(13.2)
print(messwerte[0], messwerte[-1])
print(messwerte[1:4])
print(person["name"])
print(klassen)

12.1 13.2
[11.8, 12.5, 13.0]
Ada
{'Hund', 'Katze'}


## 3. Bedingungen und Schleifen

In [3]:
temperatur = 21.5

if temperatur >= 25:
    bewertung = "warm"
elif temperatur >= 15:
    bewertung = "mild"
else:
    bewertung = "kühl"

print(bewertung)

for index, wert in enumerate(messwerte):
    print(f"Messung {index + 1}: {wert:.1f}")

mild
Messung 1: 12.1
Messung 2: 11.8
Messung 3: 12.5
Messung 4: 13.0
Messung 5: 13.2


## 4. Funktionen und List Comprehensions

In [4]:
def celsius_zu_fahrenheit(celsius: float) -> float:
    """Wandelt eine Temperatur von Celsius in Fahrenheit um."""
    return celsius * 9 / 5 + 32

fahrenheit = [celsius_zu_fahrenheit(wert) for wert in messwerte]
print(fahrenheit)

[53.78, 53.24, 54.5, 55.4, 55.76]


Type Hints wie `float` dokumentieren erwartete Typen, werden von Python aber nicht automatisch erzwungen. Funktionen sollten möglichst eine klar abgegrenzte Aufgabe erfüllen.

## 5. NumPy: Arrays statt Python-Listen

NumPy-Arrays enthalten normalerweise Werte eines gemeinsamen Datentyps. Sie erlauben schnelle, vektorisierte Berechnungen über ganze Datenblöcke und bilden die Grundlage vieler ML-Bibliotheken.

In [5]:
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=float)
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("x:     ", x)
print("Form:  ", matrix.shape)
print("Dim.:  ", matrix.ndim)
print("Typ:   ", matrix.dtype)

x:      [1. 2. 3. 4. 5.]
Form:   (2, 3)
Dim.:   2
Typ:    int64


### Vektorisierung: Rechnen ohne explizite Schleife

In [6]:
print("x * 10:  ", x * 10)
print("x²:      ", x**2)
print("Mittel:  ", x.mean())
print("Std.abw.:", x.std())
print("Summe:   ", x.sum())

x * 10:   [10. 20. 30. 40. 50.]
x²:       [ 1.  4.  9. 16. 25.]
Mittel:   3.0
Std.abw.: 1.4142135623730951
Summe:    15.0


### Indexierung, Slicing und boolesche Masken

In [7]:
daten = np.array([10, 15, 8, 22, 17, 5])

print(daten[1:4])
maske = daten >= 15
print("Maske: ", maske)
print("Gefiltert:", daten[maske])

[15  8 22]
Maske:  [False  True False  True  True False]
Gefiltert: [15 22 17]


### Achsen, Reshaping und Broadcasting

In [8]:
a = np.arange(1, 7).reshape(2, 3)
spalten_offset = np.array([10, 20, 30])

print("Matrix:\n", a)
print("Spaltensummen:", a.sum(axis=0))
print("Zeilensummen:  ", a.sum(axis=1))
print("Broadcasting:\n", a + spalten_offset)

Matrix:
 [[1 2 3]
 [4 5 6]]
Spaltensummen: [5 7 9]
Zeilensummen:   [ 6 15]
Broadcasting:
 [[11 22 33]
 [14 25 36]]


Bei einer Matrix ist `axis=0` die Aggregation **über die Zeilen hinweg** (ein Ergebnis je Spalte), `axis=1` über die Spalten hinweg (ein Ergebnis je Zeile). Broadcasting erweitert kompatible Formen virtuell, ohne die Daten manuell zu kopieren.

### Zufallszahlen reproduzierbar erzeugen

In [9]:
rng = np.random.default_rng(seed=42)
stichprobe = rng.normal(loc=100, scale=15, size=8)
print(np.round(stichprobe, 1))

[104.6  84.4 111.3 114.1  70.7  80.5 101.9  95.3]


Ein fester Seed macht ein Zufallsexperiment reproduzierbar. Das ist für Unterricht, Tests und Modellvergleiche wichtig.

## Übung

Erzeuge ein NumPy-Array mit den Prüfungswerten `[55, 72, 88, 49, 91, 67]`. Berechne Mittelwert, Minimum und Maximum. Filtere anschließend alle bestandenen Werte (mindestens 60 Punkte).

In [10]:
# Musterlösung
punkte = np.array([55, 72, 88, 49, 91, 67])
print("Mittelwert:", punkte.mean())
print("Minimum:   ", punkte.min())
print("Maximum:   ", punkte.max())
print("Bestanden: ", punkte[punkte >= 60])

Mittelwert: 70.33333333333333
Minimum:    49
Maximum:    91
Bestanden:  [72 88 91 67]


## Merksätze

- Listen sind flexibel; NumPy-Arrays sind für gleichartige numerische Daten optimiert.
- `shape` beschreibt die Form eines Arrays.
- Vektorisierung ersetzt viele Schleifen durch Operationen auf ganzen Arrays.
- Boolesche Masken filtern Daten.
- Ein fester Seed macht Zufallszahlen reproduzierbar.